#!/usr/bin/env bash
#
# Prepare the bind-mount sources for the e2e slice (docker-compose.e2e.yml).
# Idempotent; safe on a fresh CI checkout and on a dev machine (touches ONLY ./.e2e).
#
#   scripts/e2e-ci-prepare.sh           # create ./.e2e/* if missing
#   scripts/e2e-ci-prepare.sh --fresh   # also wipe per-run state (bridge store,
#                                       # notifier cursor, output, scrape state).
#
# Note --fresh does NOT drop the e2e Postgres volume; `make e2e-down` (down -v) does.
# Repeated `make e2e-run` against one slice therefore accumulates `tracks` rows — every
# assertion is keyed on a per-run company nonce, so that is harmless.
#
# Why this exists: three of the compose mounts are *files*. If a source file is
# missing, Docker silently creates a directory at that path and the app breaks at
# runtime in confusing ways. Two of those (resume.yaml, candidate_profile.yaml)
# are committed fixtures mounted directly by the override; the third — the
# pipeline dotenv — is generated here because it embeds the markserv port.
# ARTIFACT_BASE_URL must live in this dotenv, NOT in compose environment: an
# empty compose var would beat the mounted file (Config.get precedence) and
# AddArtifactUrlNode would silently no-op.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# E2E_STATE_DIR must match what docker-compose.e2e.yml interpolates (default ./.e2e).
# The multi-instance scenarios prepare a second slice from .e2e-src with this.
E2E_DIR="${E2E_STATE_DIR:-.e2e}"
E2E_DIR="${E2E_DIR#./}"

# Read the repo-root .env the same way `docker compose` does, so the port this script
# bakes into ARTIFACT_BASE_URL is the port compose actually publishes markserv on.
# Without this, E2E_MARKSERV_PORT in .env moves the container but not the URL, and the
# pipeline stamps a dead artifact_url into tracks, the completed feed, and Discord.
if [ -f .env ]; then
  # shellcheck disable=SC1091
  set -a; . ./.env; set +a
fi
MARKSERV_PORT="${E2E_MARKSERV_PORT:-18082}"

FRESH=0
for arg in "$@"; do
  case "$arg" in
    --fresh) FRESH=1 ;;
    *) echo "[e2e-prepare] unknown argument: $arg (expected --fresh)" >&2; exit 2 ;;
  esac
done

# Containers run as root, so the state they write is root-owned; a plain rm -rf fails
# on Linux for an unprivileged user. Fall back to doing the wipe inside a container.
wipe() {
  # `if`, not `rm ... && return` — an AND-list that fails under `set -e` exits the
  # script outright, which would skip the fallback this function exists for.
  if rm -rf "$@" 2>/dev/null; then return 0; fi
  echo "[e2e-prepare] state is root-owned, wiping via a throwaway container"
  docker run --rm -v "$ROOT/$E2E_DIR:/wipe" alpine:3 \
    sh -c 'rm -rf /wipe/bridge-store /wipe/notifier-state /wipe/jsearch-state /wipe/poller-secrets /wipe/output /wipe/state'
}

if [ "$FRESH" = "1" ]; then
  echo "[e2e-prepare] wiping per-run state under $E2E_DIR/"
  wipe "$E2E_DIR/bridge-store" "$E2E_DIR/notifier-state" "$E2E_DIR/jsearch-state" "$E2E_DIR/poller-secrets" "$E2E_DIR/output" "$E2E_DIR/state"
fi

mkdir -p "$E2E_DIR/output" "$E2E_DIR/state" "$E2E_DIR/bridge-store" "$E2E_DIR/notifier-state" "$E2E_DIR/jsearch-state" "$E2E_DIR/poller-secrets"

# If a previous run started compose without this script, Docker will have created a
# *directory* at the dotenv path; `cat >` would then die with "Is a directory".
if [ -d "$E2E_DIR/pipeline.env" ]; then rm -rf "$E2E_DIR/pipeline.env"; fi

cat > "$E2E_DIR/pipeline.env" <<EOF
# Generated by scripts/e2e-ci-prepare.sh — mounted at /app/.env in the e2e processor.
ARTIFACT_BASE_URL=http://127.0.0.1:${MARKSERV_PORT}
EOF

# Fail fast if the committed fixture files the override bind-mounts are missing —
# otherwise Docker would create directories in their place inside the container.
for f in services/job-fit-apply-ai-e2e/fixtures/resume.yaml \
         services/job-fit-apply-ai-e2e/fixtures/candidate_profile.yaml; do
  [ -f "$f" ] || { echo "[e2e-prepare] missing fixture: $f" >&2; exit 1; }
done

echo "[e2e-prepare] ready: $E2E_DIR/ (markserv port $MARKSERV_PORT)"
